Updated Test remote workflow

diff --git a/.github/workflows/test-load-parallel-remote.yml b/.github/workflows/test-load-parallel-remote.yml
--- a/.github/workflows/test-load-parallel-remote.yml
+++ b/.github/workflows/test-load-parallel-remote.yml
@@ -21,6 +21,30 @@ jobs:
         with:
           node-version: "20"
 
+      - name: Install Docker (for macOS)
+        run: |
+          brew install --cask docker
+          open -a Docker  # Open Docker Desktop
+          echo "Waiting for Docker to start..."
+
+          # Retry logic for Docker initialization
+          retries=5
+          while [ $retries -gt 0 ]; do
+            if docker --version; then
+              echo "Docker is ready!"
+              break
+            else
+              echo "Waiting for Docker to start... $retries retries left"
+              retries=$((retries - 1))
+              sleep 10 
+            fi
+          done
+
+          if [ $retries -eq 0 ]; then
+            echo "Docker failed to start after multiple retries. Exiting."
+            exit 1
+          fi
+
       - name: Install dependencies
         run: |
           npm cache clean --force
