GA load test

diff --git a/.github/workflows/test-load-parallel-remote.yml b/.github/workflows/test-load-parallel-remote.yml
--- a/.github/workflows/test-load-parallel-remote.yml
+++ b/.github/workflows/test-load-parallel-remote.yml
@@ -7,7 +7,7 @@ on:
 
 jobs:
   remote-test:
-    runs-on: macos-latest
+    runs-on: ubuntu-latest
     defaults:
       run:
         working-directory: signify-ts-test/
@@ -21,42 +21,42 @@ jobs:
         with:
           node-version: "20"
 
-      - name: Install Docker (for macOS)
-        run: |
-          # brew install --cask docker
-          # if [ -d "/Applications/Docker.app" ]; then
-          # echo "Docker app found, opening it..."
-          # open /Applications/Docker.app || echo "Unable to open Docker."
-          # echo "Waiting for Docker to start..."
+      # - name: Install Docker (for macOS)
+      #   run: |
+      #     # brew install --cask docker
+      #     # if [ -d "/Applications/Docker.app" ]; then
+      #     # echo "Docker app found, opening it..."
+      #     # open /Applications/Docker.app || echo "Unable to open Docker."
+      #     # echo "Waiting for Docker to start..."
 
-          # retries=10
-          # while [ $retries -gt 0 ]; do
-          #   if docker ps >/dev/null 2>&1; then
-          #     echo "Docker is ready!"
-          #     break
-          #   else
-          #     echo "Waiting for Docker daemon to start... $retries retries left"
-          #     retries=$((retries - 1))
-          #     sleep 10
-          #   fi
-          # done
+      #     # retries=10
+      #     # while [ $retries -gt 0 ]; do
+      #     #   if docker ps >/dev/null 2>&1; then
+      #     #     echo "Docker is ready!"
+      #     #     break
+      #     #   else
+      #     #     echo "Waiting for Docker daemon to start... $retries retries left"
+      #     #     retries=$((retries - 1))
+      #     #     sleep 10
+      #     #   fi
+      #     # done
 
-          # if [ $retries -eq 0 ]; then
-          #   echo "Docker daemon failed to start. Exiting."
-          #   exit 1
-          # fi
-          # else
-          #   echo "Docker app not found in /Applications. Please verify the installation."
-          #   exit 1
-          # fi
-          brew install --cask docker
-          docker_app_path=$(brew list --cask docker | grep '==> App' -A1 | tail -n 1 | awk '{ print $1 }')
-          docker_app_path="${docker_app_path/#\~/$HOME}"
+      #     # if [ $retries -eq 0 ]; then
+      #     #   echo "Docker daemon failed to start. Exiting."
+      #     #   exit 1
+      #     # fi
+      #     # else
+      #     #   echo "Docker app not found in /Applications. Please verify the installation."
+      #     #   exit 1
+      #     # fi
+      #     brew install --cask docker
+      #     docker_app_path=$(brew list --cask docker | grep '==> App' -A1 | tail -n 1 | awk '{ print $1 }')
+      #     docker_app_path="${docker_app_path/#\~/$HOME}"
 
-          sudo "$docker_app_path"/Contents/MacOS/Docker --unattended --install-privileged-components
-          open -a "$docker_app_path" --args --unattended --accept-license
-          while ! "$docker_app_path"/Contents/Resources/bin/docker info &>/dev/null; do sleep 1; done
-          docker --version
+      #     sudo "$docker_app_path"/Contents/MacOS/Docker --unattended --install-privileged-components
+      #     open -a "$docker_app_path" --args --unattended --accept-license
+      #     while ! "$docker_app_path"/Contents/Resources/bin/docker info &>/dev/null; do sleep 1; done
+      #     docker --version
 
       - name: Install dependencies
         run: |
